import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
	// params: { locale: string };
}

export default async function RootLayout({
	children,
	params,
}: RootLayoutProps): Promise<React.ReactNode> {
	const { locale } = await params;
	if (locale === "favicon.ico") return null;

	// let messages = {};
	// try {
	// 	messages = (await import(`../../shared/lib/messages/${locale}.json`))
	// 		.default;
	// } catch (error: unknown) {
	// 	console.error(`No messages for locale "${locale}"`, error);

	// 	messages = {};
	// }

	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={`antialiased`}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
