import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { NuqsAdapter } from "nuqs/adapters/next";

export const metadata: Metadata = {
	title: "Be Live Coaching",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}

export default async function RootLayout({
	children,
	params,
}: RootLayoutProps): Promise<React.ReactNode> {
	const { locale } = await params;
	if (locale === "favicon.ico") return null;

	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={`antialiased`}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<NuqsAdapter>{children}</NuqsAdapter>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
